---
abstract: 'Dump data and repopulate a database using rules'
author:
  - 'Luke Saunders <luke@shadowcatsystems.co.uk>'
build_requires:
  DBIx::Class::InflateColumn::FS: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Fixtures
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Grouped: 0.06
  Config::Any: 0.08
  DBIx::Class: 0.08102
  DBIx::Class::Schema::Loader: 0.07
  Data::Dump::Streamer: 2.05
  Data::Visitor: 0.15
  DateTime: 0.41
  DateTime::Format::MySQL: 0
  DateTime::Format::Pg: 0
  DateTime::Format::SQLite: 0.1
  File::Copy::Recursive: 0.35
  File::Path: 0
  File::Spec::Functions: 0
  Hash::Merge: 0.1
  JSON::Syck: 0.26
  MIME::Base64: 0
  Path::Class: 0.16
  Scalar::Util: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.001019
