---
abstract: 'Dump data and repopulate a database using rules'
author:
  - 'Luke Saunders <luke@shadowcatsystems.co.uk>'
build_requires:
  DBIx::Class::InflateColumn::FS: 0.01007
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Fixtures
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Grouped: 0.1001
  Config::Any: 0.23
  DBIx::Class: 0.08102
  DBIx::Class::Schema::Loader: 0.07035
  Data::Dump::Streamer: 2.05
  Data::Visitor: 0.3
  DateTime: 1.03
  DateTime::Format::MySQL: 0
  DateTime::Format::Pg: 0
  DateTime::Format::SQLite: 0.1
  File::Copy::Recursive: 0.38
  File::Path: 2.09
  File::Spec::Functions: 3.4
  Hash::Merge: 0.1
  JSON::Syck: 1.27
  MIME::Base64: 0
  Path::Class: 0.32
  Scalar::Util: 1.27
  perl: 5.6.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class-Fixtures
  homepage: http://www.dbix-class.org/
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/DBIx-Class-Fixtures.git
version: 1.001021
