--- 
abstract: ~
author: 
  - Luke Saunders <luke@shadowcatsystems.co.uk>
build_requires: 
  Test::More: 0.7
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Fixtures
no_index: 
  directory: 
    - inc
    - t
provides: 
  DBIx::Class::Fixtures: 
    file: lib/DBIx/Class/Fixtures.pm
    version: 1.000001
  DBIx::Class::Fixtures::Schema: 
    file: lib/DBIx/Class/Fixtures/Schema.pm
  DBIx::Class::Fixtures::SchemaVersioned: 
    file: lib/DBIx/Class/Fixtures/SchemaVersioned.pm
    version: 0
  DBIx::Class::Fixtures::Versioned: 
    file: lib/DBIx/Class/Fixtures/Versioned.pm
requires: 
  Class::Accessor::Grouped: 0.06
  Config::Any: 0.08
  DBIx::Class: 0.08
  DBIx::Class::Schema::Loader: 0.04004
  Data::Dump::Streamer: 2.05
  Data::Visitor: 0.15
  DateTime: 0.41
  DateTime::Format::MySQL: 0.04
  File::Copy::Recursive: 0.35
  File::Slurp: 999.13
  Hash::Merge: 0.1
  JSON::Syck: 0.26
  Path::Class: 0.16
  perl: 5.6.1
tests: t/*.t
version: 1.000001
